"""`backend/graph_lab/tests/test_engines.py`'s own row in
`.agents/plans/graph-lab/02-job-engines.md`'s Tests section: "runs
fixture-graph versions of each engine, with small bounds and CPU-only
atlas". Exercises the real `default_runner` end to end (real subprocess
supervision via `jobs.Jobs`, real `node`/Python child processes, real
`entry-lesion.mjs`/`entry-swapset.mjs`/`graph_lab.engine_atlas`) against a
tiny fixture graph (`tests/fixtures/tiny.bin.gz` -- generated by
`scripts/graph-lab/export-tiny-graph-fixture.ts` from the same
`createTinyGraph()` `tests/unit/graph-lab-entries.test.ts` already proves
round-trips through every graph-lab TS entry).

Needs `node` on PATH and a built JS bundle (`npm run graph-lab:bundle`) --
neither is available in the `graph-lab` CI job (CPU-only, no Node setup
step, matching `test_security.py`'s own "neither a GPU nor a Docker build"
design), so this whole module skips itself when either is missing rather
than failing. Run for real on a dev machine or the Spark with
`cd backend/graph_lab && uv run pytest tests/test_engines.py` after
`npm run graph-lab:bundle`. The atlas test also needs a Python
interpreter with `torch`/`flyarena_training` installed (`training/`'s own
uv-managed venv) -- set `GRAPH_LAB_TEST_ATLAS_PYTHON_BIN` to its
`bin/python3` path, or this module falls back to skipping just that test.
"""
from __future__ import annotations

import gzip
import hashlib
import json
import os
import shutil
import tempfile
import time
import unittest
from pathlib import Path

from fastapi.testclient import TestClient

from graph_lab import engine_lesion, engine_swapset
from graph_lab.service import create_app

REPO_ROOT = Path(__file__).resolve().parents[3]
FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
BUNDLE_DIR = REPO_ROOT / "backend" / "graph_lab" / "js"
SCRIPTS_DIR = REPO_ROOT / "scripts"

TOKEN = "graph-lab-test-token-0123456789"
HEADERS = {"Authorization": f"Bearer {TOKEN}"}
ALLOWED_ORIGIN = "http://127.0.0.1:5173"

NODE_BIN = shutil.which("node")
BUNDLE_BUILT = (BUNDLE_DIR / "bundle.json").is_file()
ATLAS_PYTHON_BIN = os.environ.get("GRAPH_LAB_TEST_ATLAS_PYTHON_BIN") or (
    str(REPO_ROOT / "training" / ".venv" / "bin" / "python3")
    if (REPO_ROOT / "training" / ".venv" / "bin" / "python3").is_file()
    else None
)


def _skip_unless_node_and_bundle() -> None:
    if NODE_BIN is None:
        raise unittest.SkipTest("node is not on PATH")
    if not BUNDLE_BUILT:
        raise unittest.SkipTest(f"{BUNDLE_DIR} has no bundle.json -- run `npm run graph-lab:bundle` first")


def _build_data_dir(tmp_dir: Path) -> Path:
    """A `data_dir` shaped like the real image's `/opt/graph-lab/data`, but
    built from the tiny fixture: `malecns-arena-v1.bin.gz`/`.manifest.json`
    (renamed from `tiny.*` -- `default_runner`'s manifest filename is a
    fixed constant) plus `rewiring-null-v1.json` (the tiny fixture's own
    seed-0 entry, sha-stamped into the manifest so
    `engine_lesion.regenerate_rewired_graph`'s own integrity check passes)."""
    shutil.copyfile(FIXTURES_DIR / "tiny.bin.gz", tmp_dir / "malecns-arena-v1.bin.gz")
    tiny_manifest = json.loads((FIXTURES_DIR / "tiny.manifest.json").read_text())
    rewiring_null_raw = (FIXTURES_DIR / "tiny-rewiring-null.json").read_text()
    (tmp_dir / "rewiring-null-v1.json").write_text(rewiring_null_raw)
    manifest = {
        "artifact": "malecns-arena-v1.bin.gz",
        "binarySha256": tiny_manifest["binarySha256"],
        "gzipSha256": tiny_manifest["gzipSha256"],
        "rewiringNull": {"sha256": hashlib.sha256(rewiring_null_raw.encode()).hexdigest()},
    }
    (tmp_dir / "malecns-arena-v1.manifest.json").write_text(json.dumps(manifest))
    return tmp_dir


def _build_data_dir_with_rewiring_null_sha256(tmp_dir: Path, *, rewiring_null_sha256) -> Path:
    """Like `_build_data_dir`, but the manifest's `rewiringNull.sha256` is
    caller-controlled (omitted entirely when `rewiring_null_sha256` is
    `None`) -- used to prove the published-null sha check
    (`py_scripts.require_sha256`, via `engine_lesion.regenerate_rewired_graph`/
    `engine_swapset._load_verified_published_null`) fails **closed**: a
    missing or wrong recorded hash must raise, never silently skip the
    check (a dual-review finding on an earlier version that failed open)."""
    _build_data_dir(tmp_dir)
    manifest_path = tmp_dir / "malecns-arena-v1.manifest.json"
    manifest = json.loads(manifest_path.read_text())
    if rewiring_null_sha256 is None:
        manifest.pop("rewiringNull", None)
    else:
        manifest["rewiringNull"] = {"sha256": rewiring_null_sha256}
    manifest_path.write_text(json.dumps(manifest))
    return tmp_dir


def _wait_for_terminal_status(client: TestClient, identifier: str, *, timeout: float = 60.0) -> dict:
    deadline = time.monotonic() + timeout
    status = client.get(f"/api/graph/v1/jobs/{identifier}", headers=HEADERS).json()
    while status["status"] in ("queued", "running", "cancelling") and time.monotonic() < deadline:
        time.sleep(0.1)
        status = client.get(f"/api/graph/v1/jobs/{identifier}", headers=HEADERS).json()
    return status


class LesionEngineTests(unittest.TestCase):
    def setUp(self) -> None:
        _skip_unless_node_and_bundle()
        os.environ["GRAPH_LAB_ORIGINS"] = ALLOWED_ORIGIN
        self._tmp = tempfile.TemporaryDirectory()
        self.data_dir = _build_data_dir(Path(self._tmp.name))

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def _submit(self, body: dict) -> dict:
        app = create_app(token=TOKEN, data_dir=str(self.data_dir), bundle_dir=str(BUNDLE_DIR), node_bin=NODE_BIN, scripts_dir=str(SCRIPTS_DIR))
        with TestClient(app) as client:
            response = client.post("/api/graph/v1/jobs", json=body, headers=HEADERS)
            self.assertEqual(response.status_code, 202, response.text)
            status = _wait_for_terminal_status(client, response.json()["id"])
        return status

    def test_lesion_on_biological_fixture_graph_completes_and_lesions_the_output_neuron(self):
        body = {
            "kind": "lesion",
            "graph": "biological",
            "sets": [[7]],  # tiny graph's output-population-0 neuron
            "seedStart": 1,
            "seedCount": 4,
            "ticks": 300,
        }
        status = self._submit(body)
        self.assertEqual(status["status"], "completed", status)
        result = status["result"]
        self.assertEqual(result["graph"], "biological")
        self.assertEqual(result["sets"][0]["indices"], [7])
        self.assertNotEqual(result["sets"][0]["effect"]["meanDifference"], 0)

    def test_lesion_on_rewired_seed0_regenerates_and_completes(self):
        """Proves `default_runner`'s `rewired:<seed>` branch end to end
        (previously a static 501; WP2 wires it): regenerates the graph
        into the job's own tmpfs, verifies it against the fixture's
        `rewiring-null-v1.json` entry, and scores it -- exactly the same
        pipeline as `biological`, just pointed at a freshly regenerated
        binary (a genuinely different graph from biological here -- 271
        accepted swaps; see `scripts/graph-lab/export-tiny-graph-fixture.ts`'s
        sibling generator script's own log)."""
        body = {
            "kind": "lesion",
            "graph": "rewired:0",
            "sets": [[7]],
            "seedStart": 1,
            "seedCount": 4,
            "ticks": 300,
        }
        status = self._submit(body)
        self.assertEqual(status["status"], "completed", status)

    def test_lesion_on_rewired_seed_with_no_published_entry_fails_cleanly(self):
        body = {
            "kind": "lesion",
            "graph": "rewired:1",
            "sets": [[7]],
            "seedStart": 1,
            "seedCount": 4,
            "ticks": 300,
        }
        app = create_app(token=TOKEN, data_dir=str(self.data_dir), bundle_dir=str(BUNDLE_DIR), node_bin=NODE_BIN, scripts_dir=str(SCRIPTS_DIR))
        with TestClient(app) as client:
            response = client.post("/api/graph/v1/jobs", json=body, headers=HEADERS)
            self.assertEqual(response.status_code, 500)


class SwapsetEngineTests(unittest.TestCase):
    def setUp(self) -> None:
        _skip_unless_node_and_bundle()
        os.environ["GRAPH_LAB_ORIGINS"] = ALLOWED_ORIGIN
        self._tmp = tempfile.TemporaryDirectory()
        self.data_dir = _build_data_dir(Path(self._tmp.name))

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def test_swapset_builds_scores_and_ranks_controls(self):
        # A real, legal double-edge swap on the tiny fixture graph (found
        # empirically -- see `export-tiny-graph-fixture.ts`'s sibling doc
        # comment on why this fixture needs bridge neurons at all): edges
        # 0->0 and 1->7 retarget to 0->7 and 1->0.
        body = {
            "kind": "swapset",
            "graph": "biological",
            "swaps": [{"a": 0, "b": 0, "c": 1, "d": 7}],
            "controls": 2,
            "seedStart": 1,
            "seedCount": 4,
            "ticks": 300,
        }
        app = create_app(token=TOKEN, data_dir=str(self.data_dir), bundle_dir=str(BUNDLE_DIR), node_bin=NODE_BIN, scripts_dir=str(SCRIPTS_DIR))
        with TestClient(app) as client:
            response = client.post("/api/graph/v1/jobs", json=body, headers=HEADERS)
            self.assertEqual(response.status_code, 202, response.text)
            status = _wait_for_terminal_status(client, response.json()["id"])
        self.assertEqual(status["status"], "completed", status)
        result = status["result"]
        graph_ids = {entry["graphId"] for entry in result["scores"]}
        self.assertEqual(graph_ids, {"biological", "candidate", "control-0", "control-1"})
        self.assertIsNotNone(result["controlDistribution"])
        self.assertEqual(result["controlDistribution"]["n"], 2)
        self.assertIsNotNone(result["candidateRankAmongControls"])
        self.assertEqual(result["publishedNullPercentile"], "not comparable")

    def test_swapset_rejects_an_impossible_swap_with_422(self):
        body = {
            "kind": "swapset",
            "graph": "biological",
            "swaps": [{"a": 0, "b": 0, "c": 1, "d": 1}],  # no edge 0->0 exists
            "controls": 0,
            "seedStart": 1,
            "seedCount": 4,
            "ticks": 300,
        }
        app = create_app(token=TOKEN, data_dir=str(self.data_dir), bundle_dir=str(BUNDLE_DIR), node_bin=NODE_BIN, scripts_dir=str(SCRIPTS_DIR))
        with TestClient(app) as client:
            response = client.post("/api/graph/v1/jobs", json=body, headers=HEADERS)
            self.assertEqual(response.status_code, 422)


class AtlasEngineTests(unittest.TestCase):
    def setUp(self) -> None:
        _skip_unless_node_and_bundle()
        if ATLAS_PYTHON_BIN is None:
            raise unittest.SkipTest(
                "no training/.venv/bin/python3 found -- set GRAPH_LAB_TEST_ATLAS_PYTHON_BIN"
            )
        os.environ["GRAPH_LAB_ORIGINS"] = ALLOWED_ORIGIN
        self._tmp = tempfile.TemporaryDirectory()
        self.data_dir = _build_data_dir(Path(self._tmp.name))

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def test_cpu_only_atlas_search_completes_at_the_smallest_bounds(self):
        """`02-job-engines.md`'s Tests section: "CPU-only atlas" -- never
        touches the GPU (irrelevant to the real training job's GPU usage),
        matching the plan's own smallest bounds (`population: 4`,
        `generations: 1`, `ticks: 300`)."""
        body = {
            "kind": "atlas",
            "graph": "biological",
            "searchSeed": 1,
            "population": 4,
            "generations": 1,
            "ticks": 300,
        }
        app = create_app(
            token=TOKEN,
            data_dir=str(self.data_dir),
            bundle_dir=str(BUNDLE_DIR),
            node_bin=NODE_BIN,
            scripts_dir=str(SCRIPTS_DIR),
            atlas_python_bin=ATLAS_PYTHON_BIN,
            atlas_device="cpu",
            gpu_free_bytes=lambda: 999 * 1024**3,
        )
        with TestClient(app) as client:
            response = client.post("/api/graph/v1/jobs", json=body, headers=HEADERS)
            self.assertEqual(response.status_code, 202, response.text)
            status = _wait_for_terminal_status(client, response.json()["id"], timeout=120)
        self.assertEqual(status["status"], "completed", status)
        result = status["result"]
        self.assertIn("cells", result)
        self.assertGreater(len(result["cells"]), 0)
        self.assertEqual(result["label"], "Computed on DGX (private, not published)")

    def _submit_atlas(self, graph: str) -> dict:
        body = {
            "kind": "atlas",
            "graph": graph,
            "searchSeed": 1,
            "population": 4,
            "generations": 1,
            "ticks": 300,
        }
        app = create_app(
            token=TOKEN,
            data_dir=str(self.data_dir),
            bundle_dir=str(BUNDLE_DIR),
            node_bin=NODE_BIN,
            scripts_dir=str(SCRIPTS_DIR),
            atlas_python_bin=ATLAS_PYTHON_BIN,
            atlas_device="cpu",
            gpu_free_bytes=lambda: 999 * 1024**3,
        )
        with TestClient(app) as client:
            response = client.post("/api/graph/v1/jobs", json=body, headers=HEADERS)
            self.assertEqual(response.status_code, 202, response.text)
            status = _wait_for_terminal_status(client, response.json()["id"], timeout=120)
        return status

    def test_cpu_only_atlas_on_disconnected_graph_completes(self):
        """Regression test for a dual-review finding: `expectedSha256` is
        `None` for `arm == "disconnected"` (`service.py`'s `_atlas_argv`
        never computes one for it), and `engine_atlas.py` used to put that
        `None` into the re-eval args JSON as a literal `binarySha256:
        null` -- a *present* key with the wrong value, which
        `verify-search-graph.ts` compares against the real sha and rejects,
        rather than the *absent* key its "derive it from the biological
        graph" branch actually checks for (`=== undefined`). Every
        disconnected atlas job failed until the key was omitted instead of
        nulled -- this test would have caught it (previously: "node step
        exited with status 1", now surfaced with the real reason via
        `py_scripts.describe_step_failure` if it ever regresses)."""
        status = self._submit_atlas("disconnected")
        self.assertEqual(status["status"], "completed", status)
        self.assertGreater(len(status["result"]["cells"]), 0)

    def test_cpu_only_atlas_on_rewired_seed0_completes(self):
        status = self._submit_atlas("rewired:0")
        self.assertEqual(status["status"], "completed", status)
        self.assertGreater(len(status["result"]["cells"]), 0)

    def test_atlas_reports_gpu_busy_via_the_real_app_wiring(self):
        body = {
            "kind": "atlas",
            "graph": "biological",
            "searchSeed": 1,
            "population": 4,
            "generations": 1,
            "ticks": 300,
        }
        app = create_app(
            token=TOKEN,
            data_dir=str(self.data_dir),
            bundle_dir=str(BUNDLE_DIR),
            node_bin=NODE_BIN,
            scripts_dir=str(SCRIPTS_DIR),
            atlas_python_bin=ATLAS_PYTHON_BIN,
            atlas_device="cpu",
            gpu_free_bytes=lambda: 0,
        )
        with TestClient(app) as client:
            response = client.post("/api/graph/v1/jobs", json=body, headers=HEADERS)
            self.assertEqual(response.status_code, 503)


class PublishedNullShaFailsClosedTests(unittest.TestCase):
    """`py_scripts.require_sha256` (used by both `engine_lesion.
    regenerate_rewired_graph` and `engine_swapset._load_verified_published_null`
    to verify `rewiring-null-v1.json` against the manifest's recorded
    hash) must fail **closed**: a missing or mismatched recorded hash is a
    hard error, never a silently-skipped check. Does not need `node`/a
    built bundle -- these call the Python engine functions directly, never
    reaching a subprocess."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def test_require_sha256_raises_when_expected_is_missing(self):
        from graph_lab import py_scripts

        with self.assertRaises(ValueError):
            py_scripts.require_sha256(b"anything", None, what="test data")
        with self.assertRaises(ValueError):
            py_scripts.require_sha256(b"anything", "", what="test data")

    def test_require_sha256_raises_when_expected_does_not_match(self):
        from graph_lab import py_scripts

        with self.assertRaises(ValueError):
            py_scripts.require_sha256(b"real bytes", "0" * 64, what="test data")

    def test_require_sha256_passes_when_expected_matches(self):
        import hashlib as _hashlib

        from graph_lab import py_scripts

        data = b"real bytes"
        py_scripts.require_sha256(data, _hashlib.sha256(data).hexdigest(), what="test data")  # must not raise

    def test_lesion_rewired_regeneration_fails_closed_on_missing_manifest_hash(self):
        data_dir = _build_data_dir_with_rewiring_null_sha256(Path(self._tmp.name), rewiring_null_sha256=None)
        with tempfile.TemporaryDirectory() as job_dir:
            with self.assertRaises(ValueError):
                engine_lesion.regenerate_rewired_graph(
                    scripts_dir=SCRIPTS_DIR, data_dir=data_dir, job_dir=Path(job_dir), seed=0
                )

    def test_lesion_rewired_regeneration_fails_closed_on_mismatched_manifest_hash(self):
        data_dir = _build_data_dir_with_rewiring_null_sha256(Path(self._tmp.name), rewiring_null_sha256="0" * 64)
        with tempfile.TemporaryDirectory() as job_dir:
            with self.assertRaises(ValueError):
                engine_lesion.regenerate_rewired_graph(
                    scripts_dir=SCRIPTS_DIR, data_dir=data_dir, job_dir=Path(job_dir), seed=0
                )

    def test_swapset_published_null_load_fails_closed_on_missing_manifest_hash(self):
        data_dir = _build_data_dir_with_rewiring_null_sha256(Path(self._tmp.name), rewiring_null_sha256=None)
        with self.assertRaises(ValueError):
            engine_swapset._load_verified_published_null(data_dir)

    def test_swapset_published_null_load_fails_closed_on_mismatched_manifest_hash(self):
        data_dir = _build_data_dir_with_rewiring_null_sha256(Path(self._tmp.name), rewiring_null_sha256="0" * 64)
        with self.assertRaises(ValueError):
            engine_swapset._load_verified_published_null(data_dir)


if __name__ == "__main__":
    unittest.main()
