/**
 * Shared cross-architecture floating-point tolerance for tests that compare
 * a freshly-computed arena/rate-model number against a value derived from
 * the committed golden fixtures (`tests/fixtures/golden/`), which were
 * generated on `linux-arm64`. `stepModel`/`aggregateOutputs`
 * (`connectome/model.ts`) use only `+`/`-`/`*` and are bit-exact on every
 * architecture, but the observation path (`arena/sensors.ts`'s
 * `Math.atan2`/`Math.sin`/`Math.cos`/`Math.hypot`) is not: the ECMAScript
 * spec permits implementation-defined rounding for transcendental `Math.*`
 * functions, and V8's libm is not guaranteed bit-identical across
 * architectures.
 *
 * Measured on GitHub's `ubuntu-latest` (x86_64) runner against the
 * committed arm64 fixtures (`fix/golden-cross-arch` PR diagnostic run): one
 * `observations` value (out of 4 committed seeds x 60 ticks x 8 channels)
 * differed by ~2.8e-17 absolute / ~3.1e-16 relative — about one float64 ULP
 * — and it did not propagate further: every downstream column
 * (`ratesAfter`, `outputs`, `actions`) round-trips through `Float32Array`
 * (~1.19e-7 relative precision), which absorbs a perturbation that small.
 * Every other committed file regenerated byte-identical on x86_64. See
 * `tests/unit/golden-traces.test.ts` (the primary regression gate this
 * tolerance was derived for) and `docs/architecture.md`'s "Determinism
 * scope" note.
 */

/**
 * Architecture the committed golden fixtures were generated on. An exact
 * (zero-tolerance) comparison is only valid here; everywhere else, use
 * `numbersCloseEnough`/`diffCloseEnough` below.
 */
export const GOLDEN_GENERATING_ARCH = 'arm64';

/**
 * Headroom over the measured divergence (this file's doc comment): roughly
 * 9 orders of magnitude over the observed ~2.8e-17 absolute / ~3.1e-16
 * relative difference, and roughly an order of magnitude over the largest
 * plausible single-ULP `Float32Array` rounding-boundary flip (~1.19e-7
 * relative) a double-precision perturbation this small could in principle
 * trigger downstream in an untested seed/tick/channel combination. Still
 * far below the magnitude a real behavior change in the arena/rate model
 * would produce.
 */
export const FLOAT_ABS_TOLERANCE = 1e-6;
export const FLOAT_REL_TOLERANCE = 1e-6;

/**
 * `expected`/`actual` are close enough per `FLOAT_ABS_TOLERANCE`/
 * `FLOAT_REL_TOLERANCE` — except when both are integers (`Number.isInteger`),
 * which must match exactly. This is what keeps every discrete/count value
 * (ticks, seed, substeps, respawn counts, food-pickup/hazard-contact
 * counts, graph index/offset arrays, `rngState`, ...) an exact regression
 * gate even off `GOLDEN_GENERATING_ARCH`, with no need to name each field:
 * none of them are ever fractional, and every field that legitimately is
 * fractional (positions, velocities, `distanceTravelled`/`movementScore`,
 * observations, rates, outputs, decoded actions, readout weights/outputs)
 * falls through to the tolerance check instead.
 */
export const numbersCloseEnough = (expected: number, actual: number): boolean => {
  if (Object.is(expected, actual) || expected === actual) return true;
  if (Number.isInteger(expected) && Number.isInteger(actual)) return false;
  const absDiff = Math.abs(expected - actual);
  if (absDiff <= FLOAT_ABS_TOLERANCE) return true;
  const scale = Math.max(Math.abs(expected), Math.abs(actual));
  const relDiff = scale > 0 ? absDiff / scale : absDiff;
  return relDiff <= FLOAT_REL_TOLERANCE;
};

/**
 * Recursive structural comparison built on `numbersCloseEnough`: numbers
 * use the tolerance rule above, strings/booleans/array lengths/object key
 * sets must always match exactly. Appends a human-readable mismatch
 * description per divergent leaf to `out`; an empty `out` means "matches".
 */
export const diffCloseEnough = (
  expected: unknown,
  actual: unknown,
  path: string,
  out: string[]
): void => {
  if (typeof expected === 'number' && typeof actual === 'number') {
    if (!numbersCloseEnough(expected, actual)) {
      const absDiff = Math.abs(expected - actual);
      const scale = Math.max(Math.abs(expected), Math.abs(actual));
      const relDiff = scale > 0 ? absDiff / scale : absDiff;
      out.push(
        `${path}: expected ${expected}, got ${actual} (abs diff ${absDiff}, rel diff ${relDiff}, ` +
          `over tolerance abs<=${FLOAT_ABS_TOLERANCE} or rel<=${FLOAT_REL_TOLERANCE}, or an ` +
          'integer field requiring an exact match)'
      );
    }
    return;
  }

  if (Array.isArray(expected) || Array.isArray(actual)) {
    if (!Array.isArray(expected) || !Array.isArray(actual)) {
      out.push(`${path}: expected array=${Array.isArray(expected)}, got array=${Array.isArray(actual)}`);
      return;
    }
    if (expected.length !== actual.length) {
      out.push(`${path}: expected length ${expected.length}, got ${actual.length}`);
      return;
    }
    for (let index = 0; index < expected.length; index += 1) {
      diffCloseEnough(expected[index], actual[index], `${path}[${index}]`, out);
    }
    return;
  }

  if (
    expected !== null &&
    actual !== null &&
    typeof expected === 'object' &&
    typeof actual === 'object'
  ) {
    const keys = new Set([...Object.keys(expected as object), ...Object.keys(actual as object)]);
    for (const key of keys) {
      diffCloseEnough(
        (expected as Record<string, unknown>)[key],
        (actual as Record<string, unknown>)[key],
        `${path}.${key}`,
        out
      );
    }
    return;
  }

  if (!Object.is(expected, actual)) {
    out.push(`${path}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
  }
};
