/**
 * Shared cross-architecture floating-point tolerance for tests that compare
 * a freshly-computed arena/rate-model number against a value derived from
 * the committed golden fixtures (`tests/fixtures/golden/`), which were
 * generated on `linux-arm64` with Node `GOLDEN_GENERATING_NODE` below. See
 * `docs/architecture.md`'s "Determinism scope" for the full explanation of
 * which functions are bit-exact everywhere (`connectome/model.ts`'s
 * `stepModel`/`aggregateOutputs`, which use only `+`/`-`/`*`) versus
 * architecture-sensitive (`arena/sensors.ts`'s `Math.atan2`/`Math.sin`/
 * `Math.cos`/`Math.hypot`, `arena/world.ts`'s `Math.sin`/`Math.cos`/
 * `Math.hypot` in `createWorld`/`stepWorld`, and `connectome/readout.ts`'s
 * `Math.tanh`/`Math.exp`) — this file only restates the numbers the
 * tolerance below is sized from.
 *
 * Measured on GitHub's `ubuntu-latest` (x86_64) runner against the
 * committed arm64 fixtures (`fix/golden-cross-arch` PR review, diagnostic
 * script since removed from the tree but still reachable at commit
 * `537ade4` if this branch's history survives; the numbers themselves are
 * restated here and in `docs/architecture.md` so nothing load-bearing
 * depends on that history surviving a squash-merge): one `observations`
 * value (out of 4 committed seeds x 60 ticks x 8 channels)
 * differed by ~2.8e-17 absolute / ~3.1e-16 relative — about one float64 ULP
 * — and it did not propagate further in that run: every downstream column
 * (`ratesAfter`, `outputs`, `actions`) round-trips through `Float32Array`
 * (~1.19e-7 relative precision), which absorbed a perturbation that small.
 * Every other committed file regenerated byte-identical on x86_64, and
 * `tests/unit/episode.test.ts`'s golden-vs-fresh score comparison (which
 * runs entirely through `stepWorld`'s float64 world state, not through any
 * `Float32Array`) matched exactly for every committed seed.
 *
 * Important limit of this evidence: it is an *observation* for these four
 * seeds at this graph/config, not a structural guarantee. `world.ts`'s
 * physics integrator stays in float64 throughout and feeds back into the
 * next tick's observation, so a future fixture refresh (a new seed, a new
 * graph, more ticks) could see a divergence that isn't absorbed the way
 * this one was. Two things bound the risk even so: (1) `numbersCloseEnough`
 * below still requires an *exact* match for every integer/discrete field,
 * so a perturbation that crosses a discrete threshold (a food pickup, a
 * hazard contact, a respawn) surfaces as an integer mismatch no tolerance
 * absorbs; (2) `MAX_INEXACT_LEAVES` bounds how many numeric leaves may
 * differ *above the noise floor* at all, so a *dense* divergence (the
 * signature of a real behavior regression, not sparse cross-arch noise)
 * still fails loudly even where every individual leaf is within tolerance.
 * If either trips after a legitimate fixture refresh, re-measure on the
 * real target runner before assuming it's a behavior regression — see
 * `docs/architecture.md`.
 *
 * A second, independently-measured cross-arch effect (`fix/golden-cross-arch`
 * PR review round 2) refines this: `world.ts`'s float64 feedback loop means
 * cross-arch noise is not always as sparse as the one-leaf case above. A
 * single-`Math.*`-call float64 ULP perturbation swept across every call
 * `buildGoldenFiles` makes touched up to 28 leaves in one seed file (`sin`
 * calls, whose result feeds `stepWorld`'s heading integration and so
 * compounds across ticks); the noisiest leaf found in that sweep (a
 * cancellation in a small-magnitude `observations` value) differed by
 * ~5.7e-16 absolute / ~2.9e-14 relative — still pure float64 noise, not a
 * behavior difference, just spread over more leaves and a larger relative
 * magnitude than the single-leaf case above. `LEAF_NOISE_FLOOR_REL`/
 * `LEAF_NOISE_FLOOR_ABS` below (not `MAX_INEXACT_LEAVES` itself) is what
 * absorbs this — round 3 (below) has the corrected, code-verified numbers
 * for exactly how, since the relative-only headroom this paragraph might
 * suggest (~2.9e-14 vs. a 1e-13 floor: under 4x) is not what actually
 * excludes it; the *absolute* floor does, with ~150x headroom.
 *
 * Round 3 (further empirical stress-testing during review) corrected two
 * numbers from the round-2 measurement above once checked directly against
 * the AND-combined floor rule the code implements
 * (`relDiff > LEAF_NOISE_FLOOR_REL && absDiff > LEAF_NOISE_FLOOR_ABS`):
 * the worst measured noise leaf is ~2.9e-14 relative / ~5.7e-16 absolute
 * (not ~5.2e-16 relative as first estimated from a narrower sample), and
 * it is excluded because it fails the *absolute* floor (~150x headroom),
 * not because of relative headroom (which is only ~3-4x at 2.9e-14 vs.
 * 1e-13 — thin on its own, which is exactly why the rule is AND, not OR
 * or relative-only: see `LEAF_NOISE_FLOOR_REL`'s doc comment). Separately,
 * the "weakest measured regression" figure of "44 leaves" was a
 * relative-only count; under the actual AND rule, the single weakest
 * (edge, seed-file) pair measured is 7 above-floor leaves in one file —
 * still caught overall only because the *other* seed files for that same
 * edge change (304 to 907 leaves each) exceed the budget; see
 * `MAX_INEXACT_LEAVES`'s doc comment for the corrected full picture.
 *
 * This gate is also arch-only, not OS- or Node/V8-version-aware: a
 * darwin-arm64 contributor, or a future Node upgrade on the generating
 * machine, could in principle produce a 1-ULP difference from
 * `GOLDEN_GENERATING_ARCH`'s recorded fixtures and hit the byte-exact path.
 * That would show up as a strict `toBe` failure on a large single-line JSON
 * string; if that ever happens, diff it with `diffCloseEnough` by hand to
 * confirm it is architecture noise (small, sparse) before assuming a
 * regression.
 */

/**
 * Architecture the committed golden fixtures were generated on. An exact
 * (zero-tolerance) comparison is only valid here; everywhere else, use
 * `numbersCloseEnough`/`diffCloseEnough` below.
 */
export const GOLDEN_GENERATING_ARCH = 'arm64';

/**
 * Node version the committed golden fixtures were generated with (matches
 * `.github/workflows/ci.yml`'s pinned `NODE_VERSION` and this repo's dev
 * machine). V8's `Math.*` implementations can change between Node/V8
 * releases, independent of CPU architecture — noted here so a byte-exact
 * failure on `GOLDEN_GENERATING_ARCH` after a Node upgrade is recognized as
 * the same class of issue as a cross-arch difference, not assumed to be a
 * behavior regression.
 */
export const GOLDEN_GENERATING_NODE = 'v22.22.3';

/**
 * Headroom over the measured divergence (this file's doc comment): roughly
 * 9 orders of magnitude over the observed ~2.8e-17 absolute / ~3.1e-16
 * relative difference, and roughly an order of magnitude over the largest
 * plausible single-ULP `Float32Array` rounding-boundary flip (~1.19e-7
 * relative) a double-precision perturbation this small could in principle
 * trigger downstream in an untested seed/tick/channel combination.
 *
 * This tolerance alone is *not* sufficient to rule out a real behavior
 * change: verified empirically (`fix/golden-cross-arch` PR review) that a
 * single float32-ULP change to one graph edge weight, or a `globalGain *
 * (1 + 1e-7)` change, is *individually* within this tolerance on every
 * affected leaf, yet touches dozens to thousands of leaves per seed file
 * (measured per-file range: as low as 7 in the single weakest
 * (edge, seed-file) pair — still caught overall because that same edge's
 * *other* seed files land at 304-907 — up to ~2,200 in most cases; see
 * `MAX_INEXACT_LEAVES`'s doc comment for the full, corrected numbers).
 * `MAX_INEXACT_LEAVES` below (gated by `LEAF_NOISE_FLOOR_REL`/
 * `LEAF_NOISE_FLOOR_ABS`, not by this tolerance) is the primary defense
 * against that class of regression off `GOLDEN_GENERATING_ARCH`; this
 * per-leaf tolerance is a backstop against smaller, non-dense drift.
 */
export const FLOAT_ABS_TOLERANCE = 1e-6;
export const FLOAT_REL_TOLERANCE = 1e-6;

/**
 * A numeric leaf only counts toward `MAX_INEXACT_LEAVES` if its difference
 * clears *both* floors below (relative AND absolute — the absolute floor
 * guards near-zero leaves, where a tiny absolute difference can be a huge
 * relative one without being behaviorally significant). The AND is
 * load-bearing, not redundant with using either floor alone: the worst
 * measured float64 cross-arch noise leaf (a cancellation in a
 * small-magnitude `observations` value, from a `Math.sin` call inside
 * `world.ts`'s feedback loop — see this file's header comment) was ~5.7e-16
 * absolute but ~2.9e-14 *relative* — only ~3-4x under this relative floor,
 * thin margin on its own. It is reliably excluded by the *absolute* floor
 * instead, which has ~150x headroom over that same leaf's absolute
 * difference. Do not change this to an OR, or drop the absolute half,
 * without re-measuring: either would reintroduce the round-2 false
 * positive (dense but sub-relative-floor noise from `world.ts`'s feedback
 * loop tripping `MAX_INEXACT_LEAVES` on a legitimate fixture refresh).
 * Every measured float32-ULP-scale regression clears both floors
 * comfortably (typically 1e-7 relative or denser) — see
 * `MAX_INEXACT_LEAVES`'s doc comment for the corrected per-file counts.
 */
export const LEAF_NOISE_FLOOR_REL = 1e-13;
export const LEAF_NOISE_FLOOR_ABS = 1e-13;

/**
 * Cross-arch noise, above `LEAF_NOISE_FLOOR_REL`/`LEAF_NOISE_FLOOR_ABS`, is
 * sparse: the measured divergence (this file's header comment) touched at
 * most one numeric leaf in any single committed file at the single-value
 * level, and even the denser world-feedback case (up to 28 leaves in one
 * profiled `sin` call, worst leaf ~5.7e-16 absolute / ~2.9e-14 relative)
 * stays under the floor (see `LEAF_NOISE_FLOOR_REL`'s doc comment for why
 * the *absolute* floor, not the relative one, is what actually excludes
 * it) and so is not counted at all. A real float32-ULP-scale regression is
 * dense *and* clears the floor on most affected leaves — verified
 * empirically (`fix/golden-cross-arch` PR review) by perturbing every one
 * of the 107 graph edge weights and every `inputWeight`/`outputWeight`
 * entry by one float32 ULP, one at a time: 104 of 107 single-edge changes
 * left at least one seed file with 88-1,663 above-floor leaves (comfortably
 * over budget); the single weakest measured (edge, seed-file) *pair* left
 * only 7 above-floor leaves in one file (under budget in that one file
 * alone) but the *same* edge change left its other three seed files at
 * 304-907 above-floor leaves each, so the overall check (which fails if
 * *any* committed file exceeds the budget) still catches it. Every
 * `inputWeight`/`outputWeight` entry perturbed left at least 464
 * above-floor leaves in its worst seed file. (The 3 of 107 edges that
 * escape entirely change 2 or fewer leaves under *any* rule, including the
 * pre-noise-floor one — the noise floor is not what lets them through, and
 * they are still caught by the byte-exact path on `GOLDEN_GENERATING_ARCH`.)
 * Capping the count of above-floor, not-bit-identical numeric leaves
 * (`diffCloseEnough`'s `inexactLeaves`) — on top of the per-leaf tolerance
 * — is what makes the tolerant comparison path able to catch a dense
 * regression that per-leaf tolerance alone would miss, while still
 * tolerating genuine cross-arch drift, sparse or not, as long as it stays
 * under the noise floor.
 */
export const MAX_INEXACT_LEAVES = 8;

/**
 * `expected`/`actual` are close enough per `FLOAT_ABS_TOLERANCE`/
 * `FLOAT_REL_TOLERANCE` — except when both are integers (`Number.isInteger`),
 * which must match exactly. This is what keeps every discrete/count value
 * (ticks, seed, substeps, respawn counts, food-pickup/hazard-contact
 * counts, graph index/offset arrays, `rngState`, ...) an exact regression
 * gate even off `GOLDEN_GENERATING_ARCH`, with no need to name each field:
 * none of them are ever fractional, and every field that legitimately is
 * fractional (positions, velocities, `distanceTravelled`/`movementScore`,
 * observations, rates, outputs, decoded actions, readout weights/outputs)
 * falls through to the tolerance check instead.
 */
export const numbersCloseEnough = (expected: number, actual: number): boolean => {
  if (Object.is(expected, actual) || expected === actual) return true;
  if (Number.isInteger(expected) && Number.isInteger(actual)) return false;
  const absDiff = Math.abs(expected - actual);
  if (absDiff <= FLOAT_ABS_TOLERANCE) return true;
  const scale = Math.max(Math.abs(expected), Math.abs(actual));
  const relDiff = scale > 0 ? absDiff / scale : absDiff;
  return relDiff <= FLOAT_REL_TOLERANCE;
};

/** Result of `diffCloseEnough`: `mismatches` empty means "matches within tolerance and leaf budget". */
export interface CloseEnoughDiff {
  /** Human-readable mismatch description per divergent leaf/structural difference. */
  mismatches: string[];
  /**
   * Count of numeric leaf pairs that were not bit-identical AND cleared
   * `LEAF_NOISE_FLOOR_REL`/`LEAF_NOISE_FLOOR_ABS`, whether or not they were
   * within `numbersCloseEnough`'s tolerance. Compare against
   * `MAX_INEXACT_LEAVES` to catch a dense sub-tolerance regression that
   * `mismatches` alone would miss — see this file's doc comment.
   */
  inexactLeaves: number;
}

const walk = (
  expected: unknown,
  actual: unknown,
  path: string,
  mismatches: string[],
  countInexactLeaf: () => void
): void => {
  if (typeof expected === 'number' && typeof actual === 'number') {
    // `Object.is` (not just `!==`) so NaN/NaN is never miscounted as a
    // difference -- NaN cannot occur in this schema today, but this keeps
    // the leaf count meaningful if it ever does.
    const bitIdentical = Object.is(expected, actual) || expected === actual;
    if (!bitIdentical) {
      const absDiff = Math.abs(expected - actual);
      const scale = Math.max(Math.abs(expected), Math.abs(actual));
      const relDiff = scale > 0 ? absDiff / scale : absDiff;
      // Only count toward MAX_INEXACT_LEAVES if the difference clears the
      // float64 noise floor -- see LEAF_NOISE_FLOOR_REL/ABS's doc comment.
      // A leaf within the floor is indistinguishable from cross-arch Math.*
      // rounding noise and must not count as regression evidence.
      if (relDiff > LEAF_NOISE_FLOOR_REL && absDiff > LEAF_NOISE_FLOOR_ABS) countInexactLeaf();
      if (!numbersCloseEnough(expected, actual)) {
        mismatches.push(
          `${path}: expected ${expected}, got ${actual} (abs diff ${absDiff}, rel diff ${relDiff}, ` +
            `over tolerance abs<=${FLOAT_ABS_TOLERANCE} or rel<=${FLOAT_REL_TOLERANCE}, or an ` +
            'integer field requiring an exact match)'
        );
      }
    }
    return;
  }

  if (Array.isArray(expected) || Array.isArray(actual)) {
    if (!Array.isArray(expected) || !Array.isArray(actual)) {
      mismatches.push(`${path}: expected array=${Array.isArray(expected)}, got array=${Array.isArray(actual)}`);
      return;
    }
    if (expected.length !== actual.length) {
      mismatches.push(`${path}: expected length ${expected.length}, got ${actual.length}`);
      return;
    }
    for (let index = 0; index < expected.length; index += 1) {
      walk(expected[index], actual[index], `${path}[${index}]`, mismatches, countInexactLeaf);
    }
    return;
  }

  if (
    expected !== null &&
    actual !== null &&
    typeof expected === 'object' &&
    typeof actual === 'object'
  ) {
    const expectedKeys = new Set(Object.keys(expected as object));
    const actualKeys = new Set(Object.keys(actual as object));
    for (const key of expectedKeys) {
      if (!actualKeys.has(key)) mismatches.push(`${path}.${key}: missing from actual (present in committed fixture)`);
    }
    for (const key of actualKeys) {
      if (!expectedKeys.has(key)) mismatches.push(`${path}.${key}: unexpected in actual (not in committed fixture)`);
    }
    for (const key of expectedKeys) {
      if (actualKeys.has(key)) {
        walk(
          (expected as Record<string, unknown>)[key],
          (actual as Record<string, unknown>)[key],
          `${path}.${key}`,
          mismatches,
          countInexactLeaf
        );
      }
    }
    return;
  }

  if (!Object.is(expected, actual)) {
    mismatches.push(`${path}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
  }
};

/**
 * Recursive structural comparison built on `numbersCloseEnough`: numbers
 * use the tolerance rule above (and are counted in `inexactLeaves` when not
 * bit-identical and above the noise floor, regardless of tolerance),
 * strings/booleans/array lengths/object key sets must always match exactly.
 * `path` seeds the mismatch labels (typically a filename or a short root
 * label).
 */
export const diffCloseEnough = (expected: unknown, actual: unknown, path: string): CloseEnoughDiff => {
  const mismatches: string[] = [];
  let inexactLeaves = 0;
  walk(expected, actual, path, mismatches, () => {
    inexactLeaves += 1;
  });
  return { mismatches, inexactLeaves };
};
